CC = gcc
CFLAGS = -Wall -Wextra -std=c17 -g

all: proccess1 proccess2 proccess3

proceso1: proccess1.c
	$(CC) $(CFLAGS) proccess1.c -o proccess1

proceso2: proccess2.c
	$(CC) $(CFLAGS) proccess2.c -o proccess2

proceso3: proccess3.c
	$(CC) $(CFLAGS) proccess3.c -o proccess3

clean:
	rm -f proccess1 proccess2 proccess3
