CC = gcc
CFLAGS = -Wall -Wextra -std=c17 -g

all: proceso1 proceso2

proceso1: proceso1.c
	$(CC) $(CFLAGS) proceso1.c -o proceso1

proceso2: proceso2.c
	$(CC) $(CFLAGS) proceso2.c -o proceso2

clean:
	rm -f proceso1 proceso2